site_name: API Données foncières - Documentation du client Python
site_description: Documentation du client Python pour l'API Données foncières du Cerema
site_author: Cerema
site_url: https://datafoncier.cerema.fr


theme:
  name: dsfr
  locale: fr
  # Configuration par défaut (modifiable)
  afficher_bouton_editer: true
  afficher_date_de_revision: false
  afficher_menu_lateral: true
  afficher_sommaire: false
  bouton_hautdepage: left
  include_search_page: true
  intitule: "République <br> française"
  libelle_bouton_editer: Éditer dans Gitlab Forge
  header:
    titre: "API Données foncières"
    sous_titre: "Documentation du client Python"
  footer:
    description: "Ce site est une documentation technique du client Python pour l'API Données foncières du Cerema. Pour toute question, contactez-nous à l'adresse <a href='mailto:datafoncier@cerema.fr'>datafoncier@cerema.fr</a>."
    links:
      - name: cerema.fr
        url: https://www.cerema.fr
      - name: datafoncier.cerema.fr
        url: https://datafoncier.cerema.fr
  palette:
    - scheme: default
      primary: deep orange
      accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - mkdocs-jupyter:
        include: ["*.ipynb"]
        include_requirejs: true
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [apifoncier, apifoncier.endpoints]

nav:
  - Description: index.md
  - Quickstart: 
    - Installation: quickstart/installation.md
    - Usage: quickstart/usage.md
    - Premiers exemples: quickstart/quickstart.ipynb
  - Endpoints ouverts:
    - DVF+ open-data: endpoints/dvf_opendata.md
    - Indicateurs: endpoints/indicateurs.md
    - Cartofriches: endpoints/cartofriches.md
  - Endpoints restreints:
    - Fichiers fonciers: endpoints/ff.md
    - DV3F: endpoints/dv3f.md
  - Galerie:
    - Présentation: examples/gallery.md
    - Exemples sur les friches: examples/exemple_cartofriches.ipynb
    - Exemples sur la consommation d'espace: examples/example_conso_enaf.ipynb
    - Exemples sur les indicateurs de marché : examples/example_prix.ipynb
    - Exemples sur DVF+ open-data: examples/example_dvf_opendata.ipynb    

markdown_extensions:
  - dsfr_structure.extension.all_extensions
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - tables
  - md_in_html
