site_name: API Données foncières - Documentation du client Python
site_description: Documentation du client Python pour l'API Données foncières du Cerema
site_author: Cerema
site_url: https://datafoncier.cerema.fr


theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - mkdocs-jupyter:
        include: ["*.ipynb"]
        include_requirejs: true
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [apifoncier, apifoncier.endpoints]

nav:
  - Quickstart: 
    - Description: index.md
    - Installation: installation.md
    - Usage: usage.md
  - Endpoints ouverts:
    - DVF+ open-data: dvf_opendata.md
    - Indicateurs: indicateurs.md
    - Cartofriches: cartofriches.md
  - Endpoints restreints:
    - Fichiers fonciers: ff.md
    - DV3F: dv3f.md
  - Exemples: 
    - Utilisation de cartofriches: exemple_cartofriches.ipynb

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
