site_name: API Données foncières - Documentation du client Python
site_description: Documentation du client Python pour l'API Données foncières du Cerema
site_author: Cerema
site_url: https://datafoncier.cerema.fr


theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - mkdocs-jupyter:
        include: ["*.ipynb"]
        include_requirejs: true
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [apifoncier, apifoncier.endpoints]

nav:
  - Description: index.md
  - Quickstart: 
    - Installation: quickstart/installation.md
    - Usage: quickstart/usage.md
    - Premiers exemples: quickstart/quickstart.ipynb
  - Endpoints ouverts:
    - DVF+ open-data: endpoints/dvf_opendata.md
    - Indicateurs: endpoints/indicateurs.md
    - Cartofriches: endpoints/cartofriches.md
  - Endpoints restreints:
    - Fichiers fonciers: endpoints/ff.md
    - DV3F: endpoints/dv3f.md
  - Galerie:
    - Présentation: examples/gallery.md
    - Exemples sur les friches: examples/exemple_cartofriches.ipynb
    - Exemples sur la consommation d'espace: examples/example_conso_enaf.ipynb
    - Exemples sur les indicateurs de marché : examples/example_prix.ipynb
    - Exemples sur DVF+ open-data: examples/example_dvf_opendata.ipynb    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
